debug: false
management.endpoints.web.exposure.include: "*"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: qwer!6819400
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  sql.init.mode: always

  data:
    rest:
      base-path: /api
      detection-strategy: annotated

